[colors.primary]
background = '{{color.surface.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'

[colors.cursor]
text = '{{colors.on_surface.default.hex}}'
cursor = '{{colors.on_surface_variant.default.hex}}' 
 
[colors.vi_mode_cursor]
text = '{{colors.on_surface.default.hex}}'
cursor = '{{colors.primary.default.hex}}' 
 
[colors.search.matches]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.tertiary.default.hex}}' 
 
[colors.search.focused_match]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.primary.default.hex}}' 
 
[colors.footer_bar]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.inverse_surface.default.hex}}' 
 
[colors.hints.start]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.secondary.default.hex}}' 
 
[colors.hints.end]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.secondary.default.hex}}' 
 
[colors.selection]
text = '{{color.surface.default.hex}}'
background = '{{colors.primary.default.hex}}'
 
[colors.normal]
black = '{{color.surface.default.hex}}' 
red = '{{colors.error.default.hex}}' 
green = '{{colors.primary.default.hex}}' 
yellow = '{{colors.inverse_primary.default.hex}}' 
blue = '{{colors.primary.default.hex}}' 
magenta = '{{colors.tertiary.default.hex}}' 
cyan = '{{colors.secondary.default.hex}}' 
white = '{{colors.on_surface.default.hex}}'

[colors.bright]
black = '{{color.surface.default.hex}}' 
red = '{{colors.red.default.hex}}'
green = '{{colors.green.default.hex}}'
yellow = '{{colors.yellow.default.hex}}'
blue = '{{colors.blue.default.hex}}'
magenta = '{{colors.magenta.default.hex}}'
cyan = '{{colors.cyan.default.hex}}'
white = '{{color.on_surface.default.hex}}'

[colors.dim]
black = '{{ colors.surface_dim.default.hex }}' 
red = '{{ colors.red.default.hex | set_lightness: -10.0 }}'
green = '{{ colors.green.default.hex | set_lightness: -10.0 }}'
yellow = '{{ colors.yellow.default.hex | set_lightness: -10.0 }}'
blue = '{{ colors.blue.default.hex | set_lightness: -10.0 }}'
magenta = '{{ colors.magenta.default.hex | set_lightness: -10.0 }}'
cyan = '{{ colors.cyan.default.hex | set_lightness: -10.0 }}'
white = '{{ colors.on_surface_variant.default.hex }}'
