[manager]
cwd = { fg = "#b7c9d9", bold=true}

hovered         = { fg = "#c9e6ff", bg = "#004b6f" }
preview_hovered = { underline = true, bold=true }


[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#c9e6ff", bg = "#004b6f" }

# Mode
mode_normal = { fg = "#00344e",   bg = "#95cdf7", bold = true }
mode_select = { fg = "#22323f", bg = "#b7c9d9", bold = true }
mode_unset  = { fg = "#352b4b",  bg = "#cfc0e8", bold = true }

[which]
separator       = "  "
mask            = { bg = "#1c2024" }
cand            = { fg = "#95cdf7" }
desc            = { fg = "#b7c9d9" }
separator_style = { fg = "#cfc0e8" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#b7c9d9" },

	# Videos
	{ mime = "video/*", fg = "#cfc0e8" },
	{ mime = "audio/*", fg = "#cfc0e8" },

	# Archives
	{ mime = "application/zip",             fg = "#ffb4ab" },
	{ mime = "application/gzip",            fg = "#ffb4ab" },
	{ mime = "application/x-tar",           fg = "#ffb4ab" },
	{ mime = "application/x-rar",           fg = "#ffb4ab" },
	{ mime = "application/x-bzip",          fg = "#ffb4ab" },
	{ mime = "application/x-bzip2",         fg = "#ffb4ab" },
	{ mime = "application/x-7z-compressed", fg = "#ffb4ab" },

	# Fallback
	{ name = "*", fg = "#95cdf7", bold=true },
	{ name = "*/", fg = "#b7c9d9", bold=true }
]
