[manager]
cwd = { fg = "#e5bfa8", bold=true}

hovered         = { fg = "#ffdcc7", bg = "#6e390e" }
preview_hovered = { underline = true, bold=true }


[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#ffdcc7", bg = "#6e390e" }

# Mode
mode_normal = { fg = "#502400",   bg = "#ffb787", bold = true }
mode_select = { fg = "#422b1b", bg = "#e5bfa8", bold = true }
mode_unset  = { fg = "#31320a",  bg = "#caca93", bold = true }

[which]
separator       = "  "
mask            = { bg = "#261e19" }
cand            = { fg = "#ffb787" }
desc            = { fg = "#e5bfa8" }
separator_style = { fg = "#caca93" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#e5bfa8" },

	# Videos
	{ mime = "video/*", fg = "#caca93" },
	{ mime = "audio/*", fg = "#caca93" },

	# Archives
	{ mime = "application/zip",             fg = "#ffb4ab" },
	{ mime = "application/gzip",            fg = "#ffb4ab" },
	{ mime = "application/x-tar",           fg = "#ffb4ab" },
	{ mime = "application/x-rar",           fg = "#ffb4ab" },
	{ mime = "application/x-bzip",          fg = "#ffb4ab" },
	{ mime = "application/x-bzip2",         fg = "#ffb4ab" },
	{ mime = "application/x-7z-compressed", fg = "#ffb4ab" },

	# Fallback
	{ name = "*", fg = "#ffb787", bold=true },
	{ name = "*/", fg = "#e5bfa8", bold=true }
]
