# ALSA Sound
audio_output {
    type "alsa"
    enabled "yes"
    always_on "yes"
    name "ALSA Sound Device"
}

audio_output {
    type "pulse"
    enabled "no"
    always_on "yes"
    name "Pulseaudio Sound Server"
}

audio_output {
    type "pipewire"
    enabled "no"
    always_on "yes"
    name "PipeWire Sound Server"
}

audio_output {
    type "fifo"
    enabled "yes"
    always_on "yes"
    name "Audio Visualizer feed"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}

audio_output {
    type "httpd"
    enabled "yes"
    always_on "yes"
    name "HTTPD Audio Server"
    encoder "vorbis"
    port "8000"
    # bind_to_address "0.0.0.0"
    bitrate "320"
    format "44100:16:2"
    mixer_type "software"
    max_clients "0"
}

