#!/bin/sh
[ "${TERM:-none}" = "linux" ] && \
    printf '%b' '\e]P0101417
                 \e]P1fbb0d8
                 \e]P291d5ad
                 \e]P3d5c871
                 \e]P49ecafc
                 \e]P5aac7ff
                 \e]P689d0ed
                 \e]P7e0e3e8
                 \e]P8101417
                 \e]P9f97fc0
                 \e]PA6cc791
                 \e]PBc9b94a
                 \e]PC6daffa
                 \e]PD77a5ff
                 \e]PE5dbee6
                 \e]PFe0e3e8
                 \ec'
