#!/bin/bash

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export XDG_RUNTIME_DIR="/run/user/$(id -u)"
export BACKUP_DIR="${BACKUP_DIR:-$HOME/backup}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

for file in "$XDG_CONFIG_HOME/shell/"{exports,paths}; do
	  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
