[config.wallpaper]
command = "swww"
arguments = [
    "img",
    "--resize", "crop",
    "--filter", "Lanczos3",
    "--fill-color", "000000",
    "--transition-fps", "60",
    "--transition-duration", "3",
    "--transition-type", "random",
    "--transition-bezier", "0.4,0.2,0.4,1.0"
]

[config.custom_colors]
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
orange = "#fab387"
blue = "#89b4fa"
cyan = "#89dceb"
magenta = "#b4befe"

[config.custom_keywords]
rounded = "16"
rounded_xs = "4"
rounded_sm = "8"
rounded_md = "12"
rounded_lg = "16"
rounded_xl = "20"
rounded_2xl = "24"
rounded_3xl = "28"

font_sans = "NotoSans-Regular"
font_serif = "NotoSerif-Regular"
font_mono = "JetBrainsMonoNerdFont-Regular"

[templates.tty]
input_path = "./templates/tty.sh"
output_path = "~/.config/shell/colors"
# post_hook = "sh ~/.config/shell/colors"

[templates.kitty]
input_path = "./templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "pkill -SIGUSR1 kitty"

[templates.gtk3]
input_path = "./templates/gtk.css"
output_path = "~/.config/gtk-3.0/colors.css"

[templates.gtk4]
input_path = "./templates/gtk.css"
output_path = "~/.config/gtk-4.0/colors.css"

[templates.qt5ct]
input_path = "./templates/qtct.conf"
output_path = "~/.config/qt5ct/colors/matugen.conf"

[templates.qt6ct]
input_path = "./templates/qtct.conf"
output_path = "~/.config/qt6ct/colors/matugen.conf"

[templates.hyprland]
input_path = "./templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.hyprswitch]
input_path = "./templates/style.css"
output_path = "~/.config/hyprswitch/colors.css"

[templates.ags]
input_path = "./templates/ags.scss"
output_path = "~/.config/ags/style/colors.scss"

[templates.waybar]
input_path = "./templates/colors.css"
output_path = "~/.config/waybar/colors.css"
# post_hook = "pkill -SIGUSR2 waybar"

[templates.swaync]
input_path = "./templates/colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"

[templates.rofi]
input_path = "./templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.zathura]
input_path = "./templates/zathura"
output_path = "~/.config/zathura/colors"

[templates.imv]
input_path = "./templates/imv"
output_path = "~/.config/imv/config"

[templates.vencord]
input_path = "./templates/vencord.css"
output_path = "~/.config/Vencord/themes/matugen.css"

[templates.rmpc]
input_path = "./templates/rmpc-theme.ron"
output_path = "~/.config/rmpc/themes/matugen.ron"

[templates.yazi]
input_path = "./templates/yazi.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.btop]
input_path = "./templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"

[templates.pywalfox]
input_path = "./templates/pywalfox.json"
output_path = "~/.cache/wal/colors.json"
post_hook = "pywalfox update"
